language: node_js
node_js:
  - '0.11'
install:
  - curl -s https://gist.githubusercontent.com/philopon/d45eb98d5976c6531217/raw/download-latest-purescript.sh | bash
  - tar xvf linux64.tar.gz
  - export PATH=`pwd`/purescript:$PATH
  - npm install
  - bower update
env:
  global:
  - secure: cPodTdrFrrFb+FPbR+W+ekyAZBh9/vYXw59faJYDiCFMd1q9tjuf8BXqkbw3cw2DIbKzCFyYjKm1KOaB76SSwSwR8R4nzimC+f1vHr3fecID1YJtBDkYwB1FD6BL6izEgT4a0KAZTK8zuYPODvzVp1Dkh5VeaTWboqFuUMOEz44=
  - secure: N0p2JsjQKSeUqnLYoH6mAMIc1SdYJ7GxmpFfhfQ5BMLHiORJM2+haUk8fsFGgglqnrmUSawdErdvk/3F36d1SuiPY3c8NV8VAsHYvRVxRdyQY+r++0ewNar/rBf39UTcBBb6XW9/xwLJ6gmyefABoqwK//ZZ054u5RieIydJDQY=
